### ISSUE TITLE
'unit2_moused_over_x' must be assigned before beeing used

### ISSUE THREAD

**Issue by gfgtdf** [ProditorMagnus/Ageless-for-1-11#12]
on 1.13 ageless gives a `'unit2_moused_over_x' must be assigned before beeing used` warning. You coudl fix this by accessing these global variables using rawget, but for 1.12 (where this erro sppears) i reccomend just to use the [set_menu_item]synced=no feature here instead of select events.

**Comment by ProditorMagnus** [comment]
I will check out synced=no. If it works for observers properly, then I will remove the selection-based opening.

**Comment by gfgtdf** [comment]
it does, but it's 1.13 only you you'n need to kee the old one for wesnth 1.12.

**Comment by ProditorMagnus** [comment]
Added workaround for 1.13, for 1.14 will switch to synced=no.

**Comment by ProditorMagnus** [comment]
Current implementation has side effect of disabling feeding.

**Comment by gfgtdf** [comment]
uh how that?

**Comment by ProditorMagnus** [comment]
I use on_event without passing on its argument.

**Comment by gfgtdf** [comment]
hmm ok but that sounds like a trivial thing to fix, note that it does not only break feeding but anything else that uses on_event.
