### ISSUE TITLE
Investigation: something fishy going on with Ukian Green Witch?

### ISSUE THREAD

**Issue by vgaming** [ProditorMagnus/Ageless-for-1-11#15]
I've got OOS in multiplayer game. It happened at turn 29, on Creep Wars map. I'm not sure it's Ageless-s fault, but here are some details anyway:

It happened after I had a non-standard upgrade dialog for "Ukian Seeress". I chose "Ukian Green Witch". At the same time, Creep Wars code decided that I was dead, not alive, petrified me, but failed to move me to side starting position. (Maybe it succeeded, but some other code has put me back.)

Creep Wars code ref: https://github.com/vgaming/CreepWars/blob/a345b6760a3252b074b508bd2a95b17b586f5a34/lua/leader_limbo.lua#L30

Replay (re-packaged as zip to be supported by github files): 

[Creep_Wars_narrow_0.11.zip](https://github.com/ProditorMagnus/Ageless-for-1-11/files/1648834/Creep_Wars_narrow_0.11.zip)

Game on replays server:
the bug: replays.wesnoth.org/1.12/20180120/Creep_Wars_narrow_0.11.15-1_Turn_29_(96296).bz2
continuation of the game: replays.wesnoth.org/1.12/20180120/Creep_Wars_narrow_0.11.15-1_Turn_52_(96348).bz2

**Comment by ProditorMagnus** [comment]
Reading the code, variations need prefix for race and movetype.

**Comment by ProditorMagnus** [comment]
Might be that creep war expects unit able to move in order to place it somewhere.

**Comment by vgaming** [comment]
@ProditorMagnus it uses `put_unit`, so I guess remaining movement is irrelevant. Also, having 0MP during a battle is pretty common, should've happen in every other game (but it doesn't).

**Comment by ProditorMagnus** [comment]
Most other units are able to move at least somewhere on map.

**Comment by vgaming** [comment]
@ProditorMagnus well, I'm not sure about terrain, but there's still that fact: it was dead from CW point of view, but I had upgrade dialog (which kinda means it survived) and it remained alive visually. My opponent saw the unit as just survived, without petrifying stuff.

**Comment by ProditorMagnus** [comment]
Fixed movetype, if there is something further then comment.

**Comment by vgaming** [comment]
Close the issue until more details come up then?
