### ISSUE TITLE
Feature request: do not give "quick" trait to max_movement=0 leaders

### ISSUE THREAD

**Issue by vgaming** [ProditorMagnus/Ageless-for-1-11#16]
Following the discussion online. Ageless Era currently uses this filter:
```
            [filter]
                canrecruit=yes
                formula="$this_unit.max_moves<5"
            [/filter]
```
to decide whether to give "quick" trait to leaders.

The proposal is to filter out units that have max_moves == 0, thereby leaving only 0 < max_moves < 5.

**Comment by vgaming** [comment]
May be a subtask of https://github.com/ProditorMagnus/Ageless-for-1-11/issues/14

@ProditorMagnus feel free to close or do how you see fit with this issue.

**Comment by ProditorMagnus** [comment]
Yes, commented there already.

**Comment by vgaming** [comment]
// Fixed the issue locally in Creep Wars, too. I'm now setting guard max_moves and moves to 0 each AI turn. Would also help with add-ons like "Bonus Spam" (that could otherwise give the guard some movement).
