### ISSUE TITLE
Shadow Priest issues

### ISSUE THREAD

**Issue by vgaming** [ProditorMagnus/Ageless-for-1-11#17]
1. it seems to appear at RPG era, yet it is lvl2.

2. It has an upgrade called "Darkelf Summoner". The "summoner" however does not have any plague-like weapons. It is unclear why he is given that name then. Maybe he misses an intended weapon special?

3. Since BLOODMAGIC is a macro, would it make sense to include DAMAGE parameter to the description?
"When this attack hits offensively it harms the caster"
->
"When this attack hits offensively it deals 4 damage to the caster"  (though IDK how to replace a single number in text in WML with a macro parameter)

EDIT: fixed typo.

**Comment by ProditorMagnus** [comment]
RE has no RPG version

**Comment by vgaming** [comment]
What is "RE"? The Shadow Priest is a unit you can see right now on the battlefield (the online game you're in now), and it's lvl2, and the Era is Ageless RPG for sure.

**Comment by vgaming** [comment]
I've written a code to spot all lvl2 units in Ageless RPG by the way, here is a list I've got:
```
lvl2 unit in Ageless Era:	AE_agl_deep_Minotaur
lvl2 unit in Ageless Era:	AE_ext_monsters_Wingless_Dragon
lvl2 unit in Ageless Era:	AE_efm_freemen_Roc
lvl2 unit in Ageless Era:	AE_efm_highlanders_Elephant
```

Code itself (note for myself):
```lua
for _, v in ipairs(era_array) do
	if wesnoth.unit_types[v].level > 1 then
		print("lvl2 unit in Ageless Era:", v)
	end
end
```

**Comment by ProditorMagnus** [comment]
Fixed RE rpg and heroes, part 2 and 3 changes should go through RE.

**Comment by vgaming** [comment]
I do not understand what RE is TBH.
Feel free to close the issue if it's solved though.

**Comment by ProditorMagnus** [comment]
Rashy Era.
