### ISSUE TITLE
"bloodlust" ability needs description update for unpoison

### ISSUE THREAD

**Issue by vgaming** [ProditorMagnus/Ageless-for-1-11#19]
It seems that the "Blood Warrior" berserker guy is unpoisoned when it kills. Would be good to add this information to it's "bloodlust +5" ability.

**Comment by ProditorMagnus** [comment]
Needs to be checked against current EoMa, and if exists there too, notify them too.

**Comment by ProditorMagnus** [comment]
Fixed for ageless, havent looked EoMa situation.
