### ISSUE TITLE
Primevalist Celebrant can have "fearless" ability

### ISSUE THREAD

**Issue by vgaming** [ProditorMagnus/Ageless-for-1-11#21]
Primevalist Celebrant can have "fearless" ability, even though he's neutral.

That seems somewhat counter-intuitive. Needless to say, this ability is also totally useless.

**Comment by ProditorMagnus** [comment]
Do you have any solutions for that?

**Comment by vgaming** [comment]
@ProditorMagnus disallow "fearless" ability for that unit? Like elves race does. Is it easy/possible?

**Comment by ProditorMagnus** [comment]
So that unit should lost trait when leveling up?

**Comment by vgaming** [comment]
Ah, didn't think of that. I presume it's not that easy to do. Maybe remove "fearless" as a possible trait from the base unit? I think I'd go this way, but I don't insist.

**Comment by ProditorMagnus** [comment]
It is possible to disallow trait for unit type. But I really see no reason for this change - current behavior just encourages advancing nonfearless units to celebrant.

**Comment by vgaming** [comment]
Well IDK, fearless neutral unit confused me. But OK, no reason to debate if I don't really have any new arguments, or proposals.

**Comment by sevu** [comment]
If this would have been an EoM unit I would have removed it from the unit_line for consistency.
Do I get it right that there is no real reason to not remove fearless besides that we would need to come up with an alternative buff for these units?

**Comment by ProditorMagnus** [comment]
Another consideration would be that archaic era can have large enough upstream changes that I would delete and import it again, losing ageless-specific changes.

Though if that alternative would be more fitting, then it should be suggested for original as well.

**Comment by sevu** [comment]
It would be ideal to have changes in ageless upstream as well.

In this particular case, it seems that the difference with archaic is the fearless trait gives as well unplaguagble there.
A more handy solution for that may be to use the original mainline trait, and a musthave trait with no name & description for these units (=the whole race?), and increasing the num_traits by one.
The fact that they are unplaguagble is then maybe better mentioned in the race description or/and as special notes. Though - some players will not read them beforehand and miss this information, e.g. when they see the unit the first time - any ideas on that, is that for the worse or better?
I may make a PR for it someday [not soon]

Btw, does the Primevalist Celebrant even need a buff for not having fearless / having useless fearless?

**Comment by ProditorMagnus** [comment]
Unplaguable has before been implemented as undead_variation.

**Comment by doofus-01** [comment]
At the time I applied that, I didn't know of a way to silently give the unplague-able trait, other than the way I did.  Is there now a better way?  The Follower line can certainly lose Fearless, it will give the Fighter line more ... spice.  I don't understand @ProditorMagnus's last comment.

**Comment by ProditorMagnus** [comment]
It is old way, but should still work https://github.com/wesnoth/wesnoth/blob/1.10/data/core/units/monsters/Giant_Mudcrawler.cfg#L21.

**Comment by doofus-01** [comment]
Interesting, thanks.  That looks like off-label usage though, behaviour that may change at any time.
