### ISSUE TITLE
Giant Rat Duo has "ambush" ability, though Help says it shouldn't have

### ISSUE THREAD

**Issue by vgaming** [ProditorMagnus/Ageless-for-1-11#25]
subj. I tested the Giant Rat Duo once, and it seems that the unit has "ambush". The type information does not say anything about "ambush" though.

I did a "save->replay->save" cycle though, dunno if a wesnoth bug could sneak in. Probably not though.

Thoughts?

**Comment by ProditorMagnus** [comment]
It is bug of help browser/whatever you used to check if it should have ambush.

It has multiple [abilities] in same [unit_type]. Will see if I can support selecting such cases with https://github.com/ProditorMagnus/WML_tree_tools. I think I cant specifically select tags with two subtags of same name, but I can later go over that list.

**Comment by vgaming** [comment]
@ProditorMagnus I just pressed "D" to invoke Help on the unit. Should that have worked?

**Comment by ProditorMagnus** [comment]
No idea, I guess multiple [abilities] should be accepted or rejected based on celmin schema validation.

**Comment by ProditorMagnus** [comment]
>        _abilities="optional abilities"
So it is undefined behavior.

**Comment by vgaming** [comment]
hmm.. Not like I really understood that. So the ability has a chance to activate itself and has a chance NOT to activate itself at unit creation time?
If the answer is Yes, I wonder why have such an ability at all, why not make it 100% persistent.

**Comment by ProditorMagnus** [comment]
> Will see if I can support selecting such cases with https://github.com/ProditorMagnus/WML_tree_tools. I think I cant specifically select tags with two subtags of same name, but I can later go over that list.

That is plan yes.

**Comment by vgaming** [comment]
TBH I still don't understand what's happening. But Okay, I guess the bug report itself isn't that useful then.

**Comment by ProditorMagnus** [comment]
It serves as reminder that I should locate this situation.

**Comment by vgaming** [comment]
Ok, cool :+1:

**Comment by sevu** [comment]
There is indeed a bug in the help. E.g. if a unit has [advancement]s (or was it [advance]) ALL abilities it can get that way are displayed in the help.

**Comment by ProditorMagnus** [comment]
This is not from advancement, the unit has that ability always. https://github.com/ProditorMagnus/Ageless-for-1-11/blob/master/units/EE_units/monsters/Giant_Rat_Duo.cfg#L31-L50

**Comment by sevu** [comment]
Guess it will work if it would in one single `[abilities]` tag, or if the second starts as `[+abilities]`.
Well, the ageless problem, to much aged code... and not enough people who do maintain it.

**Comment by ProditorMagnus** [comment]
Duplicate abilities {'AE_bem_calydonians_Tassiarch', 'AE_mag_Mystic_Warrior', 'AE_ext_monsters_Giant_Rat_Trio', 'AE_ext_monsters_Giant_Rat_Duo', 'AE_bem_calydonians_Strategos'}

Duplicate resistance {'AE_mrc_avians_Savior', 'AE_mrc_avians_Dove', 'AE_mrc_avians_Nestguard', 'AE_mag_Void_Mage', 'AE_mrc_avians_Razorwing', 'AE_mag_Great_Warlock', 'AE_mrc_avians_Bladewing', 'AE_mag_Rhami', 'AE_agl_vlk_Ghost_Warrior', 'AE_mrc_avians_Shell', 'AE_mag_DarkApostle'}

Duplicate defense {'AE_mag_Steamcopter', 'AE_mag_Balloon', 'AE_mag_Water_God', 'AE_mag_Water_Avatar', 'AE_mag_Dark_Portal', 'AE_efm_darklanders_Canoe', 'AE_rhy_fh_Huntsman', 'AE_rhy_fh_Alpha_Wolf', 'AE_rhy_fh_Ranger', 'AE_rhy_fh_Trapper', 'AE_mag_Water_Elemental', 'AE_rhy_fh_Druid', 'AE_mag_Mechanical_Dragon', 'AE_rhy_fh_Young_Wolf', 'AE_mag_Heavy_Balloon', 'AE_rhy_fh_Ancient_Druid', 'AE_rhy_fh_Forest_Wolf'}

**Comment by ProditorMagnus** [comment]
There are more tags to check. Weapon specials need special handling to allow multiple attacks with special.
