### ISSUE TITLE
unknown unit types

### ISSUE THREAD

**Issue by sevu** [ProditorMagnus/Ageless-for-1-11#28]
This errors are shown when loading a mainline scenario with ageless being installed.
I guess that should not happen because MULTIPLAYER is not defined there
```
Unknown unit type : AE_rhy_dw_Fighter
Unknown unit type : Bone Knight
```

**Comment by ProditorMagnus** [comment]
What you mean by mainline scenario?

**Comment by sevu** [comment]
Hmmm... it happens not when loading the scenario - it happens when opening the help, I used UtBS.

**Comment by ProditorMagnus** [comment]
Will investigate if those strings exist in WML dump when preprocessed without MULTIPLAYER. Other than that, it is part of #14.

**Comment by ProditorMagnus** [comment]
Without MULTIPLAYER ageless only creates WML
[textdomain]
	name="wesnoth-Ageless_Era"
	path="data/add-ons/Ageless_Era/translations"
[/textdomain]
