### ISSUE TITLE
Faction icons

### ISSUE THREAD

**Issue by sevu** [ProditorMagnus/Ageless-for-1-11#7]
The new Faction Icons from EoMa are to big.
Cutting them to only display the logo is better. Or maybe an unit like before?

Maybe we could postpone the release to tomorrow, updating the language files didn't work out of the box, and I'm having no time today anymore.

**Comment by ProditorMagnus** [comment]
I guess just logo would work.

Ok, tomorrow then.

**Comment by ProditorMagnus** [comment]
However, unit type id freeze is in place now.

**Comment by sevu** [comment]
ok

**Comment by ProditorMagnus** [comment]
Let me know once I can generate wml document snapshot for release.

**Comment by sevu** [comment]
ok, i will

**Comment by sevu** [comment]
Would be done. Only the images are missing.

**Comment by ProditorMagnus** [comment]
Started generating it then.

**Comment by ProditorMagnus** [comment]
I hope that translations work with <<>> instead of "" as well. Otherwise it's more work for me looking for places that absolutely need <<>>. - Seems to work.

**Comment by ProditorMagnus** [comment]
Uncompress this to Ageless_Era/ https://expirebox.com/download/975ba04caf4adba05239a727815f2cf5.html

**Comment by ProditorMagnus** [comment]
Wait... magenta doesnt get colored.

**Comment by ProditorMagnus** [comment]
I guess I need to cut those images?

**Comment by ProditorMagnus** [comment]
Using 1.13 broke everything, generating another version.

**Comment by sevu** [comment]
That's a great idea to preprocess the era.

**Comment by ProditorMagnus** [comment]
From my tests I got  
normal ageless loading time: 1:22, 1:08, 1:34
singlefile ageless loading time: 0:26, 0:29, 0:19, 0:19

**Comment by ProditorMagnus** [comment]
zookeeper was worried about interaction with GPL, so I had to include both preprocessed and normal version to server.

**Comment by sevu** [comment]
If all big eras would include this, loading speed problems would be gone.
Including the normal wml is good because I think a lot of people look occasionally at code here and there.

**Comment by ProditorMagnus** [comment]
Creating these requires nontrivial use of wesnoth -p, that might be limiting for most people.

**Comment by sevu** [comment]
Maybe you can document it somewhere. Though EoM is small, I will give it a try there too.
In general we must report some things to other devs.
nontrivial use of -p ... I suppose it's a single, very long line?

**Comment by ProditorMagnus** [comment]
Two lines actually, just using it in expected way doesnt collect all core macros, so first command to preprocess and save core, and second to preprocess addon.

**Comment by ProditorMagnus** [comment]
https://forums.wesnoth.org/viewtopic.php?p=613516#p613516

**Comment by sevu** [comment]
Looks interesting. I will try to implement it when I have some free time again.

**Comment by ProditorMagnus** [comment]
I still messed up generating that one, had to upload 4.18a.

**Comment by sevu** [comment]
Happens ;)
I realized that other eras have different ways to load
as SP campaign
as multiplayer
and, if wesnoth is started with -d option, one can start SP campaigns in MP.
oh, and the editor mode.
